using System.IO;
using System.Xml.Serialization;

namespace AssembliesByRepo.Logic.Space
{
    /// <summary>
    /// Helper class for old style csproj files.
    /// Internal classes generated by copying XML and pasting special as classes.
    /// </summary>
    public class SdkStyleCsProj
    {
        public static AssInfo AssInfoFrom(string csProjPath)
        {
            using (var fileStream = File.Open(csProjPath, FileMode.Open))
            {
                XmlSerializer serializer = new XmlSerializer(typeof(SdkStyleCsProj.Project));
                var parsed = (SdkStyleCsProj.Project)serializer.Deserialize(fileStream);

                return new AssInfo
                {
                    AssType = AssInfo.AssTypes.Dll,
                    AssName = string.IsNullOrWhiteSpace(parsed.PropertyGroup.AssemblyName)
                        ? Path.GetFileName(csProjPath)
                        : parsed.PropertyGroup.AssemblyName,
                    CsProjPath = csProjPath,
                };
            }
        }

        // Note: Internal classes below this point generated by copying XML and pasting special as classes.
        // ---------------------------------

        // NOTE: Generated code may require at least .NET Framework 4.5 or .NET Core/Standard 2.0.
        /// <remarks/>
        [System.SerializableAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        [System.Xml.Serialization.XmlRootAttribute(Namespace = "", IsNullable = false)]
        public partial class Project
        {

            private ProjectPropertyGroup propertyGroupField;

            private string sdkField;

            /// <remarks/>
            public ProjectPropertyGroup PropertyGroup
            {
                get
                {
                    return this.propertyGroupField;
                }
                set
                {
                    this.propertyGroupField = value;
                }
            }

            /// <remarks/>
            [System.Xml.Serialization.XmlAttributeAttribute()]
            public string Sdk
            {
                get
                {
                    return this.sdkField;
                }
                set
                {
                    this.sdkField = value;
                }
            }
        }

        /// <remarks/>
        [System.SerializableAttribute()]
        [System.ComponentModel.DesignerCategoryAttribute("code")]
        [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true)]
        public partial class ProjectPropertyGroup
        {

            private string targetFrameworkField;

            private string assemblyNameField;

            private string rootNamespaceField;

            /// <remarks/>
            public string TargetFramework
            {
                get
                {
                    return this.targetFrameworkField;
                }
                set
                {
                    this.targetFrameworkField = value;
                }
            }

            /// <remarks/>
            public string AssemblyName
            {
                get
                {
                    return this.assemblyNameField;
                }
                set
                {
                    this.assemblyNameField = value;
                }
            }

            /// <remarks/>
            public string RootNamespace
            {
                get
                {
                    return this.rootNamespaceField;
                }
                set
                {
                    this.rootNamespaceField = value;
                }
            }
        }


    }
}
